describe('Secret Menu with Cypress Studio', () => {
  beforeEach(() => {
    cy.visit('/secret-menu');
  });

  it('does stuff generated by Cypress Studio', () => {
    /* ==== Generated with Cypress Studio ==== */
    cy.get('#minimum-rating-visibility').click();
    cy.get('#restaurant-visibility-filter').select('KFC');
    cy.get('.mx-auto').click();
    cy.get('.whereToOrder > .cell').should('have.text', 'KFC');
    /* ==== End Cypress Studio ==== */
  });
});
